version: "3.7"
name: elastic
services:
   mysql:
      container_name: mysql
      image: mysql:8
      ports:
         - 3306:3306
      volumes:
         - ~/apps/mysql:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=12345
         - MYSQL_DATABASE=bestinsurance_truclient
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
      container_name: elasticsearch
      restart: always
      environment:
         - xpack.security.enabled=false
         - discovery.type=single-node
      ulimits:
         memlock:
            soft: -1
            hard: -1
         nofile:
            soft: 65536
            hard: 65536
      cap_add:
         - IPC_LOCK
      volumes:
         - ./elasticsearch-data:/usr/share/elasticsearch/data
      ports:
         - 9200:9200
      depends_on:
         - mysql
   kibana:
      container_name: kibana
      image: docker.elastic.co/kibana/kibana:8.4.1
      restart: always
      environment:
         - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
         - 5601:5601
      depends_on:
         - elasticsearch
   logstash:
      container_name: logstash
      image: logstash:1.0
      restart: always
      depends_on:
        - elasticsearch
        - mysql