CREATE TABLE client_contact (
    `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(50) UNIQUE NOT NULL,
    `name` VARCHAR(30) NOT NULL,
    `email` VARCHAR(50),
    `signingAuth` BOOLEAN DEFAULT null,
    `clientId` BIGINT NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`clientId`) REFERENCES `client`(`id`)
);