CREATE TABLE client (
    `id` BIGINT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(50) UNIQUE NOT NULL,
    `name` VARCHAR(30) NOT NULL,
    `email` VARCHAR(50) NOT NULL,
    `deleted` BOOLEAN DEFAULT false,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);